### PR TITLE
Fix parsing of strings containing `%` and `%%`

### LINKED ISSUE #63: String containing a single `%` is parsed incorrectly
Given the following:

Screenshot 2024-05-06 at 10 27 18

The current code generates as so:

```swift
/// A fixed string containing the % symbol
public static func percentageDiscount(_ arg1: UInt) -> Self {
    Self (
        key: "percentageDiscount",
        defaultValue: ###"50\###(arg1)ff"###,
        table: "Localizable",
        locale: .current,
        bundle: .current
    )
}
```

But this is wrong, it should be:

```swift
public static var percentageDiscount: Self {
    Self (
        key: "percentageDiscount",
        defaultValue: ###"50% off"###,
        table: "Localizable",
        locale: .current,
        bundle: .current
    )
}
```

### PR DESCRIPTION
**Pull request by liamnichols**
Closes #63

### CODE REVIEW

File: Sources/StringExtractor/StringParser.swift [hunk 1]
```diff
@@ -68,16 +74,17 @@ extension StringParser {
         }
 
         // Optional, precision information
-        Optionally(.anyOf("-+# 0"))
+        Optionally(.anyOf("-+"))
```
Comment (liamnichols) [inline Sources/StringExtractor/StringParser.swift:77]: I removed space because while it's valid for printf specifiers, it's confusing.. For example:

```swift
String(format: "50% off") // "500ff"
```

It's not really used for localized strings, so there is no need to factor it in/ Same with `0` and `#`
